// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "path";
import { defineConfig, env } from "prisma/config";

const datasourceUrl = path.join(__dirname, 'data.db')


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: 'file:' + datasourceUrl
  },
});
